name: Deploy Secure Model Artifact Store

on:
  push:
    branches:
      - main  # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (for Lambda dependencies if needed)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install zip utility
        run: sudo apt-get install -y zip

      - name: Package Lambda functions
        run: |
          cd lambda
          zip function.zip upload_model.py download_model.py
          cd ..

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init & Apply - Infra
        working-directory: ./infra
        run: |
          terraform init
          terraform validate
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

      - name: Terraform Init & Apply - CloudTrail
        working-directory: ./infra/cloudtrail
        run: |
          terraform init
          terraform validate
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
